version: 0.1

phases:
  install:
    commands:
      - echo Installing RSpec...
      - gem install rspec
  pre_build:
    commands:
      - echo `curl -i http://sgtest-env.us-east-1.elasticbeanstalk.com/`
      - IP=$(curl http://checkip.amazonaws.com)/32
      - echo $IP
      - aws ec2 authorize-security-group-ingress --group-id sg-f196ce8c --protocol tcp --port 80 --cidr $IP
      - echo `curl -i http://sgtest-env.us-east-1.elasticbeanstalk.com/`
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Ruby code...
      - rspec HelloWorld_spec.rb
      - echo $Name
      - echo $OS
      - aws s3 mb s3://codebuidtest987
      - echo `aws s3 ls` 
  post_build:
    commands:
      - echo Build completed on `date`
      - aws ec2 revoke-security-group-ingress --group-name awseb-e-2bvw385mbb-stack-AWSEBLoadBalancerSecurityGroup-13NC27HU823O0 --protocol tcp --port 80 --cidr $IP
artifacts:
  files:
    - HelloWorld.rb
